services:
  - type: web
    name: nzoo-immo
    env: node
    rootDir: project
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 18
